### PR TITLE
Add fine-tuned result of codellama-7b-instruct-hf_qlora

### PR DESCRIPTION
**Pull request by qidanrui**
Add fine-tuned result of codellama-7b-instruct-hf with the QLoRA method into `docs/eval_llm_result.md`
image

### CODE REVIEW

**Review by wangzaistone — APPROVED** [review]
great work!

**Comment by qidanrui** [comment]
> great work!

Thanks!

**Comment by qidanrui** [comment]
Related to issue #108

**Comment by wangzaistone** [comment]
> > great work!
> 
> Thanks! Could you please help me to merge this PR into the `main` branch? Because I do not have the write access of this project. Thanks again!

Thank you very much for your submission. If you're interested in the project and are willing to contribute together, I'd be delighted to connect with you on WeChat.  my wechat is  dabing3520.  Or you can find me in the DB-GPT project's WeChat group under the name "wangzai", we are happy to welcome for your join!

**Comment by wangzaistone** [comment]
@qidanrui  Could you tell us the params of the results , especially  the epoch, max_length , and so on

**Comment by qidanrui** [comment]
> @qidanrui Could you tell us the params of the results , especially the epoch, max_length , and so on

Certainly sure! Parameters are shown in the following figure which is from `train_sft.sh`
捕获
The training machine is V100 with 16G GPU memory on Google Colab.
Any other questions are welcome! Thanks!

**Comment by oushu1zhangxiangxuan1** [comment]
> > @qidanrui Could you tell us the params of the results , especially the epoch, max_length , and so on
> 
> Certainly sure! Parameters are shown in the following figure which is from `train_sft.sh` 捕获 The training machine is V100 with 16G GPU memory on Google Colab. Any other questions are welcome! Thanks!

Have you encounterd problems like https://github.com/eosphoros-ai/DB-GPT-Hub/issues/106?
I'm wondering why, may caused by cudadriver/cudatoolkit/cudnn/pytorch versions? Could you share us your versions realated? Thanks!

**Comment by wangzaistone** [comment]
> #106

the default param is not trained enough for codellama, it's better to get the final result from this set params  as follows :
```bash

CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --model_name_or_path Your_download_CodeLlama-13b-Instruct-hf_path \
    --do_train \
    --dataset example_text2sql_train \
    --max_source_length 2048 \
    --max_target_length 512 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --template llama2 \
    --lora_rank 64 \
    --lora_alpha 32 \
    --output_dir dbgpt_hub/output/adapter/code_llama-13b-2048_epoch8_lora \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 50 \
    --save_steps 2000 \
    --learning_rate 2e-4 \
    --num_train_epochs 8 \
    --plot_loss 
    ```

**Pull request merged**
