### PR TITLE
Feature/bird zf

### PR DESCRIPTION
**Pull request by moutozf**
Add Bird dataset data process and evaluation scripts

### CODE REVIEW

**Comment by qidanrui** [comment]
@moutozf Thanks a lot for the contribution! Just two comments:
* Can we still keep the default dataset here as Spider?
Screen Shot 2023-12-29 at 7 12 15 PM

* Does the `decode_json_file` part still works for Spider?
Screen Shot 2023-12-29 at 7 13 07 PM

@wangzaistone I'm no so familiar with BIRD dataset. Could you please help me review and test the evaluation file in this PR? Thanks!

**Comment by qidanrui** [comment]
@moutozf I've reformat the code style to pass through the `black` style checking.

**Review by qidanrui — COMMENTED** [review]
@moutozf Hi, Fan! Thanks a lot for the contribution! Just two comments:
* Can we still keep the default dataset here as Spider?
Screen Shot 2023-12-29 at 7 12 15 PM

* Does the `decode_json_file` part still works for Spider?
Screen Shot 2023-12-29 at 7 13 07 PM

@wangzaistone I'm no so familiar with BIRD dataset. Could you please help me review and test the evaluation file in this PR? Thanks!

**Comment by moutozf** [comment]
> @moutozf Hi, Fan! Thanks a lot for the contribution! Just two comments:
> 
> * Can we still keep the default dataset here as Spider?
>   Screen Shot 2023-12-29 at 7 12 15 PM
> * Does the `decode_json_file` part still works for Spider?
>   Screen Shot 2023-12-29 at 7 13 07 PM
> 
> @wangzaistone I'm no so familiar with BIRD dataset. Could you please help me review and test the evaluation file in this PR? Thanks!

@qidanrui I have change the default dataset to Spider and it still works after change for sql data process

**Comment by moutozf** [comment]
> @moutozf Hi, Fan! Thanks a lot for the contribution! Just two comments:
> 
> * Can we still keep the default dataset here as Spider?
>   Screen Shot 2023-12-29 at 7 12 15 PM
> * Does the `decode_json_file` part still works for Spider?
>   Screen Shot 2023-12-29 at 7 13 07 PM
> 
> @wangzaistone I'm no so familiar with BIRD dataset. Could you please help me review and test the evaluation file in this PR? Thanks!

@qidanrui I have reset the dataset to Spider and add output name in config for decoder json file function

**Review by qidanrui — APPROVED** [review]

**Pull request merged**
