### PR TITLE
Chatglm3 support and predict param update 

### PR DESCRIPTION
**Pull request by wangzaistone**
1、 feat : add support for chatglm3 train and predict . [issues/168](https://github.com/eosphoros-ai/DB-GPT-Hub/issues/168)
2、release experiment about the chatglm3 qlora and lora  training  result   .
3、fix defect and  expose the input prediction data set file parameters to the user, and adjust the input and output file parameter specifications of the prediction.  [ssues/173](https://github.com/eosphoros-ai/DB-GPT-Hub/issues/173)

### CODE REVIEW

**Comment by wangzaistone** [comment]
the code run  pass screenshot  : 
image

**Comment by csunny** [comment]
Great～， Regarding the benchmark results of ChatGPT-3. The evaluation on Spider without fine-tuning and ft-results could be updated into the [baseline](https://github.com/eosphoros-ai/DB-GPT-Hub/blob/main/dbgpt_hub/baseline/baseline.json)

**Review by zhanghy-sketchzh — APPROVED** [review]
good job！

**Comment by junewgl** [comment]
great！

**Comment by qidanrui** [comment]
Great!

**Pull request merged**
