### PR TITLE
Add automatic releasenote generator

### PR DESCRIPTION
**Pull request by qidanrui**
RT.

### CODE REVIEW

**Review by wangzaistone — APPROVED** [review]
great  work

**Comment by wangzaistone** [comment]
@qidanrui  " This branch has conflicts that must be resolved "

**Comment by qidanrui** [comment]
> @qidanrui " This branch has conflicts that must be resolved "

Sure. I'll solve it and propose a new commit.

**Review by wangzaistone — COMMENTED** [review]
great ~

**Review by wangzaistone — COMMENTED** [review]
LGTM

**Review by wangzaistone — APPROVED** [review]

**Pull request merged**
