### PR TITLE
feat: add one-shot train

### PR DESCRIPTION
**Pull request by junewgl**
The code currently only supports ohe-shot, and other shots are similar.

First, generate one-shot data
`sh dbgpt_hub/scripts/gen_train_eval_data.sh `
The output directory will generate four json:
- example_text2sql_train.json
- example_text2sql_dev.json
- example_text2sql_train_one_shot.json
- example_text2sql_dev_one_shot.json

Then, start train
`sh dbgpt_hub/scripts/train_sft.sh`

### CODE REVIEW

**Comment by qidanrui** [comment]
May I ask what is the meaning of `one-shot training`? @junewgl

**Comment by junewgl** [comment]
> May I ask what is the meaning of `one-shot training`? @junewgl

Of course, I'm happy to answer your questions. Here are the related experiments of few-shot. One-shot gives LLM an example when prompting and tells LLM how to answer the question. @qidanrui

**Comment by qidanrui** [comment]
I've read and tested the uploaded code. Great work!

**Review by qidanrui — APPROVED** [review]

**Comment by wangzaistone** [comment]
LGTM ~

**Comment by qidanrui** [comment]
@wangzaistone Could you please also test the training process? Thanks!

**Comment by qidanrui** [comment]
@wangzaistone Can we merge this PR?

**Comment by wangzaistone** [comment]
> @wangzaistone Can we merge this PR?
Sure, just now in a meeting ,have merged~

**Pull request merged**
