### PR TITLE
update torch version to 2.1.0

### PR DESCRIPTION
**Pull request by qidanrui**
Update the torch version in `Poetry` to 2.1.0 to solve issue #134

### CODE REVIEW

**Review by csunny — DISMISSED** [review]
r+

**Review by wangzaistone — COMMENTED** [review]
when run  " poetry run sh dbgpt_hub/scripts/gen_train_eval_data.sh" 
still report error ~

**Review by wangzaistone — APPROVED** [review]
Great !

**Comment by qidanrui** [comment]
I've added the Cuda-related packages into the `pyproject.toml` manually. Sorry for the previous errors.

**Pull request merged**
